<?php

namespace Etk\Bundle\SFPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * monedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class monedaRepository extends EntityRepository
{
}
