#Id, Fecha, P1userId, P1userId,  isAI, Vida J1, Vida j2, Energia J1, Energia j2
Games\TCGBundle\Entity\game:
    type: entity
    table: game
    id:
        id:
            type: binary
            nullable: false
            fixed: false
            id: true
            generator:
                strategy: UUID
    lifecycleCallbacks:
      prePersist: [ generateId ]                
    fields:
        P1UserId:
            type: string
            nullable: false
            length: 255
            fixed: false
        P2UserId:
            type: string
            nullable: true
            length: 255
            fixed: false
        AiPlayer:
            type: boolean
            nullable: true
        P1Life:
            type: float
            nullable: false
        P1Energy:
            type: float
            nullable: false
        P2Life:
            type: float
            nullable: false
        P2Energy:
            type: float
            nullable: false
        P1LastMove:
            type: datetime
            nullable: false
        P2LastMove:
            type: datetime
            nullable: false
            
            
