<?php

namespace Etk\Bundle\UsuariosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivationlinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivationlinkRepository extends EntityRepository
{
}
