services:
#    etk_usuarios.example:
#        class: Etk\Bundle\UsuariosBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    etk_admin.usuarios:
        class: Etk\Bundle\UsuariosBundle\Service\Usuarios
        arguments: [ "@doctrine.orm.entity_manager" , "@templating", "@mailer" ]
     #   arguments: [@service_id, "plain_value", %parameter%]