etk_noticias_index:
    path:     /pruebas
    defaults: { _controller: EtkNoticiasBundle:Default:index }

etk_contact:
    path:     /contacto
    defaults: { _controller: EtkNoticiasBundle:Default:contact }

etk_noticias_test:
    path:     /intro
    defaults: { _controller: EtkNoticiasBundle:Default:parallax1 }
