services:
#    etk_noticias.example:
#        class: Etk\Bundle\NoticiasBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    etk_admin.noticias:
        class: Etk\Bundle\NoticiasBundle\Service\Noticias
        arguments: [ "@doctrine.orm.entity_manager" , "@templating", "@mailer" ]